data:
  class_path: datasets.PedestrianDataModule
  init_args:
    data_dir: "/media/rasho/Data 1/Arbeit/dataset/wildtrack"  # "/usr/home/tee/Developer/datasets/WILDTRACK"
    train_cameras: [2,3,4,5,6]
    test_cameras: [0,1]

    kwargs:
      num_cameras: 2

model:
  resolution: [120, 4, 360]  # Y,Z,X
  bounds: [0, 1440, 0, 480, 0, 200]   # xmin,xmax,ymin,ymax,zmin,zmax
                                      # from https://www.kaggle.com/datasets/aryashah2k/large-scale-multicamera-detection-dataset
                                      # The “positionID” in .json files are indexed on a 480x1440 grid, X-first, with a 2.5cm spacing.
                                      # The origin is (-3.0,-9.0) Therefore, X = -3.0 + 0.025ID%480 Y = -9.0 + 0.025ID/480
  depth: [100, 0, 2000]
  num_cameras: 2
  num_ids: 1201
  experiment_name: 'log_name_holder_test_1'
