data:
  class_path: datasets.PedestrianDataModule
  init_args:
    data_dir: "/home/s-jiang/Documents/datasets/MultiviewX"  # "/usr/home/tee/Developer/datasets/WILDTRACK"
    train_cameras: [0,2,4]
    test_cameras: [0,2,4]

model:
  resolution: [160, 2, 250]  # Y,Z,X
  bounds: [0, 1000, 0, 640, 0, 2]  # xmin,xmax,ymin,ymax,zmin,zmax
  depth: [100, 0, -20]
  num_cameras: 3
  num_ids: 350  # id: 0~349
  gating_threshold: 30000
  experiment_name: 'log_name_holder_test_1'
