model:
  model_name: 'Segnet_e'
  encoder_name: 'Encoder_resnet18_fpn_v2' # 'res18' 'fasterrcnn_resnet50_fpn' Encoder_resnet18_fpn_v2

  kwargs:
    # encoder_latent_dim: 256
    latent_dim: 256  # the same as encoder_latent_dim

    waighting_mode: 'None'
    feat_direction_mode: 'None'
    aggregate_mode: 'mean'