model:
  model_name: 'SplitSegnet'

  kwargs:
    encoder_latent_dim: 256
    latent_dim: 256  # the same as encoder_latent_dim
    use_avgpool: True
    waighting_mode: 'concat'
    feat_direction: 'concat'


