data:
  class_path: datasets.PedestrianDataModule
  init_args:
    data_dir: "/home/s-jiang/Documents/datasets/MultiviewX" # "/usr/home/tee/Developer/datasets/MultiviewX"
    train_cameras: [0,1,2,3,4,5]
    test_cameras: [0,1,2,3,4,5]
model:
  resolution: [160, 2, 250]  # Y,Z,X
  bounds: [0, 1000, 0, 640, 0, 2]  # xmin,xmax,ymin,ymax,zmin,zmax
  depth: [100, 0, -20]
  num_cameras: 6
  num_ids: 350  # id: 0~349
  gating_threshold: 30000