#seed_everything: 1337
trainer:
  accelerator: gpu
  devices: [3] # (int) 0~5
  max_epochs: 100 # 100
  accumulate_grad_batches: 8
  gradient_clip_val: 0.5
  check_val_every_n_epoch: 1
  log_every_n_steps: 5
  # logger:
  #   class_path: lightning.pytorch.loggers.TensorBoardLogger
  #   init_args:
  #     save_dir: "./lightning_logs3"
  #     name: "res50_0" # coco_pretrained_experiment local_retrained_experiment 
  #     version: null
  callbacks:
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: ModelCheckpoint
      init_args:
        monitor: val_loss
        save_top_k: 5
        mode: min
        save_last: true
        filename: "model-{epoch:02d}-{val_loss:.2f}"

  # tuner:
  #tun  scale_batch_size: True